### ISSUE TITLE
The call is ambiguous between the following methods or properties

### ISSUE THREAD

**Issue by jokerxvier** [kaistseo/UnitySocketIO-WebSocketSharp#13]
Hi how can i fixed the error below?

Assets/UnitySocketIO-WebSocketSharp-master/SocketIO/websocket-sharp/AuthenticationResponse.cs(301,16): error CS0121: The call is ambiguous between the following methods or properties: `WebSocketSharp.Ext.IsNullOrEmpty(this string)' and `WebSocketSharp.Ext.IsNullOrEmpty(this string)'

**Comment by Wolfos** [comment]
You have both the source code and the compiled DLL's in your project, you'll need only the DLL's (or the source code if you're going to edit it).
